import Head from 'next/head';
import { Inter } from '@next/font/google';
import Styles from '../styles/index.module.sass';
import { useRouter } from 'next/router';
import { MouseEvent, useEffect, useState } from 'react';
import React from 'react';
import axios from 'axios';

const inter = Inter({ subsets: ['latin'] });

interface Film {
  name: string;
  author: string;
}

const Home: React.FC = () => {
  const router = useRouter();

  const [favorites, setFavorites] = useState<Film[]>([]);

  useEffect(() => {
    const fetchFavorites = async () => {
      try {
        const response = await axios.get(`${process.env.API_URL}/api/getLists`);
        const fetchedFavorites: Film[] = response.data;

        const paddedFavorites = [
          ...fetchedFavorites,
          ...Array.from({ length: 5 - fetchedFavorites.length }).map(() => ({
            name: '...',
            author: '...',
          })),
        ];
        setFavorites(paddedFavorites);
      } catch (error) {
        console.error('Failed to fetch favorites:', error);
      }
    };
    fetchFavorites(); 
  }, []);

  const favoriteElements = favorites.map((film, index) => {
    const isClickable = film.name !== '...';
    return (
      <li key={index}>
        <button disabled={!isClickable}>
          {film.name} - {film.author}
        </button>
      </li>
    );
  });

  const handleCreateNewClick = (e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    router.push('/createNew');
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={Styles.container}>
        <h1>Favorite Films List</h1>
        <div className={Styles.home}>
          <button className={Styles.new} onClick={handleCreateNewClick}>
            <p>Create New</p>
          </button>

          <ul>{favoriteElements}</ul>
        </div>
      </main>
    </>
  );
};

export default Home;
